BEGIN {
 FS = "( |\t|=)+"
 print "/* Automatically generated by ini2resid.awk. Do not edit. */"
 n = "_" toupper(name)
 gsub(/\./, "_", n)
 print "#ifndef " n
 print "#define " n
}
/^\[/ {gsub(/\[|\]/, ""); s = $1}
($1 == "INDEX") {print "#define " s " " $2}
END {
 print "#endif"
}
